### ISSUE TITLE
every second '* * * * * *' throws an exception

### ISSUE THREAD

**Issue by mchudinov** [HangfireIO/Cronos#23]
Parsing of "* * * * * *" (six stars here, markdown hides a star) throws an exception
CronExpression.Parse("* * * * * * *")

Cronos.CronFormatException: Unexpected character '*'.
   at Cronos.CronExpression.ThrowFormatException(String format, Object[] args) in C:\projects\cronos\src\Cronos\CronExpression.cs:line 1014
   at Cronos.CronExpression.Parse(String expression) in C:\projects\cronos\src\Cronos\CronExpression.cs:line 91

**Comment by mchudinov** [comment]
It works with only  CronFormat.IncludeSeconds. Maybe as it is intended. Close the item then.

**Comment by mchudinov** [comment]
Use CronFormat.IncludeSeconds to avoid exception.
